FROM python:3.8

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTONUNBUFFERED 1

RUN sh -c "wget -O - https://dl.openfoam.org/gpg.key | apt-key add -"
RUN apt-get update
RUN apt-get -y install software-properties-common
RUN add-apt-repository http://dl.openfoam.org/ubuntu
RUN apt-get update
# RUN apt-get -y install openfoam7

WORKDIR /app

COPY requirements.txt /app/
RUN pip install -r requirements.txt

COPY . /app/
WORKDIR /app/OFoamDjango

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

EXPOSE 8000
